### ISSUE TITLE
ValueError: Unsupported target: dpex

### ISSUE THREAD

**Issue by zjin-lcf** [IntelPython/numba-dpex#855] opened 2022-12-22 13:15 UTC
I tried to run the vectorize.py example. The error may be expected. 

```
  File "/opt/intel/oneapi/intelpython/latest/lib/python3.9/site-packages/numba/np/ufunc/decorators.py", line 123, in wrap
    vec = Vectorize(func, **kws)
  File "/opt/intel/oneapi/intelpython/latest/lib/python3.9/site-packages/numba/np/ufunc/decorators.py", line 37, in __new__
    imp = cls.get_target_implementation(kws)
  File "/opt/intel/oneapi/intelpython/latest/lib/python3.9/site-packages/numba/np/ufunc/decorators.py", line 27, in get_target_implementation
    raise ValueError("Unsupported target: %s" % target)
ValueError: Unsupported target: dpex
```

**Comment by diptorupd** [comment] 2023-01-08 19:05
@zjin-lcf the vectorize feature is broken and presently getting redesigned. We are targeting the next release for the fix.

**Comment by diptorupd** [comment] 2023-01-08 19:07
Closing as duplicate of #807

**Closed by diptorupd** 2023-01-08 19:07 UTC
