### ISSUE TITLE
Single precision Numba applications fail on GPUs that support single precision operations

### ISSUE THREAD

**Issue by adarshyoga** [IntelPython/numba-dpex#361] opened 2021-05-14 00:10 UTC
One GPUs that support only single precision operations (int32, float32), a numba application that uses only single precision data is failing. This is because Numba generates double precision values for some of the intermediate operations in the kernel.

To reproduce run [blackscholes in dpbench](https://github.com/IntelPython/dpbench/tree/main/numba/blackscholes/GPU) with single precision inputs on DG1.

**Comment by diptorupd** [comment] 2023-12-10 16:31
The only current workaround for the issue is to explicitly use a 32-bit dtype when defining arrays used in a kernel. The change has already been done in dpbench.

Doing a larger fix will involve changing Numba internals and have a dedicated code generation target that supports only 32-bit code generation by default.

I am closing this ticket. Once we decide if a dedicated 32-bit code generation target will be created, we will open a separate issue to track the work.

**Closed by diptorupd** 2023-12-10 16:31 UTC
