### ISSUE TITLE
Warning in tests: `Unable to join threads to shut down before fork()`

### ISSUE THREAD

**Issue by PokhodenkoSA** [IntelPython/numba-dpex#16] opened 2020-11-19 09:31 UTC
Warning message:
```
...
test_dppl_func_device_array (numba_dppy.tests.dppl.test_dppl_func.TestDPPLFunc) ... Unable to join threads to shut down before fork(). It can break multithreading in child process
Unable to join threads to shut down before fork(). It can break multithreading in child process
ok
test_dppl_func_ndarray (numba_dppy.tests.dppl.test_dppl_func.TestDPPLFunc) ... Unable to join threads to shut down before fork(). It can break multithreading in child process
Unable to join threads to shut down before fork(). It can break multithreading in child process
Unable to join threads to shut down before fork(). It can break multithreading in child process
Unable to join threads to shut down before fork(). It can break multithreading in child process
ok
...
```

**Comment by PokhodenkoSA** [comment] 2020-11-19 10:12
@reazulhoque @diptorupd 
Did you see anything similar before?

**Comment by Hardcode84** [comment] 2020-11-19 22:14
This is from numba TBB fork safety handling code, it is probably benign in our particular case, but it is currently no way to get rid of it (see also relevant discussion https://github.com/numba/numba/pull/6208#pullrequestreview-486047104). 

Proper fix would be probably to add new api to Numba to temporarily disable fork safety checks and wrap all 'safe' usages (e.g. new process creation)

**Comment by diptorupd** [comment] 2023-02-19 17:09
Closing as the issue is not present any more. But, it might crop up again as the issue is related to TBB.

**Closed by diptorupd** 2023-02-19 17:09 UTC
Labels: bug, tests, numba
