### ISSUE TITLE
Pairwise distance numpy implementation fails

### ISSUE THREAD

**Issue by adarshyoga** [IntelPython/numba-dpex#100] opened 2020-08-30 23:08 UTC
Pairwise distance numpy implementation contains calls np.sum with non-default axis and reshape functions which fail execution.

[Here ](https://github.com/IntelPython/dpbench/blob/main/dpbench/benchmarks/pairwise_distance/pairwise_distance_numba_dpex_n.py)is the link to the failing pairwise distance numpy implementation.

----------- Error -----
```
No implementation of function Function(<class 'numba_dpex.dpnp_iface.stubs.dpnp.sum'>) found for signature:

sum(array(float64, 2d, C), axis=Literal[int](1))
```

**Comment by diptorupd** [comment] 2023-02-12 18:41
Duplicate of #784

**Closed by diptorupd** 2023-02-12 18:41 UTC
