### ISSUE TITLE
L2 norm implementation fails with NotImplementedError

### ISSUE THREAD

**Issue by adarshyoga** [IntelPython/numba-dpex#975] opened 2023-03-20 20:23 UTC
The [l2 norm numba implementation](https://github.com/adarshyoga/dpbench/blob/main/dpbench/benchmarks/l2_norm/l2_norm_numba_dpex_n.py) with dpnp calls fails since numba-dpex does not currently support dpnp.sum calls with non-default axis. See failing code snippet below.

```
@dpjit
def l2_norm(a, d):
    sq = np.square(a)
    sum = sq.sum(axis=1)
    d[:] = np.sqrt(sum)
```

How to reproduce:
1) Follow [instructions ](https://github.com/adarshyoga/dpbench)to setup dpbench.
2) Run l2_norm - python -c "import dpbench; dpbench.run_benchmark(\"l2_norm\")"

**Comment by diptorupd** [comment] 2023-03-20 21:20
Duplicate of #784

**Closed by diptorupd** 2023-03-20 21:20 UTC
